[workspace]
authors = ["KhangDS <gausseuler159357@gmail.com>"]
channels = ["conda-forge"]
name = "Multivariate_KernelDensity_Estimators"
platforms = ["osx-arm64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
r-base = ">=4.5.2,<4.6"
